# Housing Price Prediction Using Linear Regression Small dataset

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import sklearn 
from sklearn import linear_model
import matplotlib.pyplot as plt
import math 

In [3]:
df = pd.read_csv('homeprices.csv')

In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
median_bed = math.floor(df.bedrooms.median())

In [6]:
df.bedrooms = df.bedrooms.fillna(median_bed)

In [7]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
x_train = df[['area','bedrooms','age']]
y_train = df[['price']]

In [9]:
linear = linear_model.LinearRegression()
linear.fit(x_train,y_train)

LinearRegression()

In [10]:
linear.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [11]:
linear.intercept_

array([221323.0018654])

In [12]:
linear.predict([[3000, 3, 40]])

array([[498408.25158031]])

In [13]:
acc = linear.score(x_train,y_train)

In [14]:
acc

0.9550196399325819