# Salary Prediction Using Linear Regression Small dataset Multiple Variables

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import sklearn 
from sklearn import linear_model
import matplotlib.pyplot as plt
import math
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [4]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [5]:
df.experience = df.experience.fillna('zero')

In [6]:
df.experience = df.experience.apply(w2n.word_to_num)

In [7]:
df.score = math.floor(df['test_score(out of 10)'].mean())

In [8]:
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(df.score)

In [9]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [10]:
x_train = df[['experience','test_score(out of 10)','interview_score(out of 10)']]
y_train = df[['salary($)']]

In [11]:
linear = linear_model.LinearRegression()
linear.fit(x_train,y_train)

LinearRegression()

In [12]:
linear.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [13]:
linear.intercept_

array([14992.65144669])

In [14]:
linear.predict([[2,9,6]])

array([[53713.86677124]])

In [15]:
linear.predict([[12,10,10]])

array([[93747.79628651]])

In [16]:
acc = linear.score(x_train,y_train)

In [17]:
acc

0.977013901427314